language: node_js
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
node_js:
- '6'
- '5'
- '4'
branches:
  only:
  - master
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "sandbox_SF@coveo.com"
deploy:
  provider: npm
  email: "sandbox_SF@coveo.com"
  on:
    tags: true
    repo: coveo/eslint-config-coveo
  api_key:
    secure: Hl85iXmH69MuQ6CeRsGyQ1HJgyVGQoe4HHra4Nd6gPWeNLpvp/+P5yRSnDuwQblkLG0W17jaz82WyC8dzw9s4ogRYf2cSaO5gJLATU54mWCH9OVU3psDxtQj3KW5Y6PJ9Ud0fddl2iy+w46auE8cS/UCkSFJ7zdB1bFjL111v8WLcH4TZtPmCX8PGe/uHa2iPaqX7u50eu5U7Prvnqdoxrm28TCccUelGnKkKCwm5rX7b/LBNKlZza90kN4usn0E5cADkFklHCuEebFM6zEbPeCCy0MSu7vHZVcxtMdgyGx1MR0LyXpdjyyzOjOzne7Cm98d9E6ZJ1MhzhCcbgRil/yON/vVmqSsXxzbf5AHLRwMwUQpKufdyM0OptyJJG/YGPHTax2amT+HEYSLdNBCNrMWFD9m1XA6w7lanu3onCNo8XJ3e9KGSnwJQsrMbnqX5DKuwitJRjjB9SyMcWa5AC0vyaZ7b9XRdxyZ2JFJS5FWey4zQjKbiDYVi807/Xambp199NcG8kcKqHwV+6Kbh/xl0uTb3h1yKbhO8ngQGy1Pa5pPNiqa86qir1KNjd01p9oEHrwIyyC7/oO4DlTDRXROSZ5faYcoxCPhBUndW6ems4XN05SYGLM48gHVgz9zSKB44PN2D7BZwGBTX/i8Od8ddWOpvn8DjaaaPEQxc/M=
